### PR TITLE
update docs for reference fields

### PR DESCRIPTION
**Pull request by theganyo**

### CODE REVIEW

**Review by timburks — APPROVED** [review]

**Comment by theganyo** [comment]
By the way, I didn't include the output of `make protos` because doing so changed all the proto generated files and added some new ones. Perhaps you can make sense of that @timburks ?

**Comment by timburks** [comment]
@theganyo let's regenerate those files in this PR to avoid downstream confusion. I think it will be clear to reviewers/posterity that this was a small change to the protos.

**Comment by theganyo** [comment]
@timburks Ok, I did it... and made changes to get it working and passing lint again. What I'm wondering: If you check this out and run `make protos` will we have changes again or will this be correct? Can you try it?

**Comment by timburks** [comment]
@theganyo yes, I'll try duplicating this. These are a lot more changes than I expected, I wonder how much is due to changes in the generators themselves.

**Comment by timburks** [comment]
@theganyo thanks for doing this, I've worked partly through all the implications of updating the code generators and don't think it's worth redoing all the changes you made here. Let's merge it.

**Comment by timburks** [comment]
Here's the diff that I see when I checkout this branch and rerun `make all`:
```
~/Desktop/registry$ git diff
diff --git a/rpc/admin_service.pb.go b/rpc/admin_service.pb.go
index ecd5cf3..aef4cca 100644
--- a/rpc/admin_service.pb.go
+++ b/rpc/admin_service.pb.go
@@ -21,15 +21,14 @@
 package rpc
 
 import (
-       reflect "reflect"
-       sync "sync"
-
-       longrunning "cloud.google.com/go/longrunning/autogen/longrunningpb"
        _ "google.golang.org/genproto/googleapis/api/annotations"
+       longrunning "google.golang.org/genproto/googleapis/longrunning"
        protoreflect "google.golang.org/protobuf/reflect/protoreflect"
        protoimpl "google.golang.org/protobuf/runtime/protoimpl"
        emptypb "google.golang.org/protobuf/types/known/emptypb"
        fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
+       reflect "reflect"
+       sync "sync"
 )
 
 const (
diff --git a/rpc/admin_service_grpc.pb.go b/rpc/admin_service_grpc.pb.go
index 256bccc..ac42c78 100644
--- a/rpc/admin_service_grpc.pb.go
+++ b/rpc/admin_service_grpc.pb.go
@@ -22,8 +22,7 @@ package rpc
 
 import (
        context "context"
-
-       longrunning "cloud.google.com/go/longrunning/autogen/longrunningpb"
+       longrunning "google.golang.org/genproto/googleapis/longrunning"
        grpc "google.golang.org/grpc"
        codes "google.golang.org/grpc/codes"
        status "google.golang.org/grpc/status"
diff --git a/rpc/provisioning_service.pb.go b/rpc/provisioning_service.pb.go
index e0ec820..3763144 100644
--- a/rpc/provisioning_service.pb.go
+++ b/rpc/provisioning_service.pb.go
@@ -21,14 +21,13 @@
 package rpc
 
 import (
-       reflect "reflect"
-       sync "sync"
-
-       longrunning "cloud.google.com/go/longrunning/autogen/longrunningpb"
        _ "google.golang.org/genproto/googleapis/api/annotations"
+       longrunning "google.golang.org/genproto/googleapis/longrunning"
        protoreflect "google.golang.org/protobuf/reflect/protoreflect"
        protoimpl "google.golang.org/protobuf/runtime/protoimpl"
        timestamppb "google.golang.org/protobuf/types/known/timestamppb"
+       reflect "reflect"
+       sync "sync"
 )
 
 const (
diff --git a/rpc/provisioning_service_grpc.pb.go b/rpc/provisioning_service_grpc.pb.go
index bf998e4..04e3424 100644
--- a/rpc/provisioning_service_grpc.pb.go
+++ b/rpc/provisioning_service_grpc.pb.go
@@ -22,8 +22,7 @@ package rpc
 
 import (
        context "context"
-
-       longrunning "cloud.google.com/go/longrunning/autogen/longrunningpb"
+       longrunning "google.golang.org/genproto/googleapis/longrunning"
        grpc "google.golang.org/grpc"
        codes "google.golang.org/grpc/codes"
        status "google.golang.org/grpc/status"
```

**Comment by timburks** [comment]
@theganyo since you're out today, I'll push the merge button and submit a followup PR for the small changes that seem to be remaining.

**Pull request merged**
