### PR TITLE
Replace ubuntu-latest in actions with ubuntu-22.04

### PR DESCRIPTION
**Pull request by timburks**
Feeling a bit burned by the surprise failures that led to #786, I'd like to also pin the ubuntu image used in testing to an explicit version. Any concerns?

### CODE REVIEW

**Comment by theganyo** [comment]
Counter-point: CI did its job of pointing out an issue that we might not have noticed until a user attempted an install of Postgres 15. This change will likewise ensure we don't know about any issues in new versions of ubuntu.

**Comment by theganyo** [comment]
Counter counter-point: Only testing on latest could cause us to accidentally drop support for older versions.

Arguably, we should:

1. Test on each platform version that we support.
2. Also test on latest platform version.

This way:

1. We don't accidentally rely on new features that don't exist in supported versions.
2. We can also see if there are coming support issues with future versions.

**Review by theganyo — APPROVED** [review]
Anyway, the bigger issues with our CI aside, nothing wrong with this change per se.

**Comment by timburks** [comment]
@theganyo Thanks - I think the main reason to pin is to avoid surprises that block everything until the upgrade consequence gets fixed. Compatibility testing across versions seems better to do at a different frequency - maybe a weekly "canary" run that picks up the latest versions of all dependencies so we can get a heads up and plan a response, like the issue for Postgres 15 support that I need to file...

**Comment by giteshk** [comment]
After reviewing the Github actions files, I think the ubuntu-latest is the only to define the machine to run the jobs on. 
Eventually we pick specific docker container images that run on the ubuntu-latest runner.

I don't have objections to tying to to a specific version, I just prefer the ubuntu-latest.

**Review by giteshk — APPROVED** [review]

**Pull request merged**
